language: python
cache: pip
python:
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - pytest --cov-branch --cov authark.app tests/
  - pytest --cov-branch --cov authark tests/
after_success:
  - coveralls
