language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
script:
  - mypy authark
  - pytest --cov-report term-missing --cov-branch --cov authark tests
after_success:
  - codecov --file /tmp/.coverage_authark

