summary: Register user.

tags:
  - Users

parameters:
  - in: body
    schema: 
      $ref: "#/definitions/User"

responses:
  201:
    description: "User created"


definitions:
  User:
    id: User
    title: User
    type: object
    properties:
      username:
        type: string
        example: "amlopez"
      email:
        type: string
        example: "amlopez@nubark.com"
      password:
        type: string
        example: "secret"
    