summary: Request token.

tags:
  - Tokens

parameters:
  - in: body
    schema: 
      $ref: "#/definitions/TokenRequest"

responses:
  201:
    description: "Token created"
    schema:
      $ref: "#/definitions/Token"


definitions:
  TokenRequest:
    id: TokenRequest
    title: TokenRequest
    type: object
    properties:
      username:
        type: string
        example: "amlopez"
      password:
        type: string
        example: "secret"
      client:
        type: string
        example: "data_server"
  Token:
    id: Token
    title: Token
    type: object
    properties:
      refresh_token:
        type: string
        example: "eyJhbG.eyJzdWIiOiIx.MjM5MadQssw5c"
      access_token:
        type: string
        example: "eyJhbG.kpvaG4gRMyfQ.SflKxwssw5cdfs"
  AccessTokenPayload:
    id: AccessTokenPayload
    title: AccessTokenPayload
    type: object
    properties:
      iss:
        type: string
        example: "authark.nubark.cloud"
      sub:
        type: string
        example: "e1fbaebd-6a37-4949-83b3-fb8954b07a2a"
      iat:
        type: integer
        example: 1543334000
      exp:
        type: integer
        example: 1543338055
      authorization:
        additionalProperties:
          type: object
          $ref: "#/definitions/DominionAuthorization"
  DominionAuthorization:
    id: DominionAuthorization
    title: DominionAuthorization
    type: object
    properties:
      roles:
        type: array
        items:
          type: string
      